_extends: jellyfin-meta-plugins

template: |
  <!-- Optional: add a release summary here -->
  [Plugin build can be downloaded here](https://github.com/unfedorg/jellyfin-plugin-pdfcover/releases/download/v$NEXT_MAJOR_VERSION.0.0/pdfcover_$NEXT_MAJOR_VERSION.0.0.0.zip).

  ## :sparkles: What's New

  $CHANGES
