---
name: "PDF Cover"
guid: "9c4e63f1-031b-4f25-988b-4f7d78a8b53e"
version: 1
targetAbi: "10.9.0.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Extract PDF cover Image"
description: >
  Extract cover image from PDF files for your pdf collection.

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.Pdfcover.dll"
changelog: |-
  - Initial contribute
