---
name: "PDFCover"
guid: "9e6b04c1-2181-4089-bce8-a8f0c35cef17"
version: untagged-6ede00423156e43e2c47
targetAbi: "10.11.5.0"
framework: "net9.0"
overview: "Generate PDF cover images"
description: "Generates cover images for your PDF files."
category: "Books"
owner: "unfedorg"
artifacts:
  - "Jellyfin.Plugin.PDFCover.dll"
  - "PDFtoImage.dll"
  - "SkiaSharp.dll"
  - "runtimes/linux-arm64/native/libpdfium.so"
  - "runtimes/linux-x64/native/libpdfium.so"
  - "runtimes/osx-arm64/native/libpdfium.dylib"
  - "runtimes/osx-x64/native/libpdfium.dylib"
  - "runtimes/win-arm64/native/pdfium.dll.win"
  - "runtimes/win-x64/native/pdfium.dll.win"
changelog: |-
  - Chore/remove prev releases (#23) @unfedorg
  - Prepare plugin manifest for release v2 (#22) @[github-actions[bot]](https://github.com/apps/github-actions)
